### ISSUE TITLE
Is this usable standalone?

### ISSUE THREAD

**Issue by jakoberpf** [ONLYOFFICE/Kubernetes-Docs#137]
Heylo,

I am quite new to onlyoffice galaxy and only deployed it as docker-compose deployment (install.sh script) for testing. As an permament solution I would like to move to kubernetes instead and tried out this helm deployment, but can't get out of the example view and can't save anything. Is this deployment usable as standalone or just supposed to be integrated into an application or eg. the community server?

In that case I would likely have to build a complete workspace deployment, so community, documents, (mail) and control-panel umbrella chart?

As the documents server image can use an integreated rabbitmq and postgres, these don't have to be deployed if just one instance of the document server is running? So as an idea, rebuild the docker deployment as an helm chart? (no-ha and so on, i know)

Sorry for the maybe obvious and blunt questions.

Thanks for any feedback,
Jakob

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

> I am quite new to onlyoffice galaxy and only deployed it as docker-compose deployment (install.sh script) for testing. As an permament solution I would like to move to kubernetes instead and tried out this helm deployment, but can't get out of the example view and can't save anything.

Which images do you use?
Are Redis, RabbitMQ and PostgreSQL deployed?
Have you set up PVCs?

>  Is this deployment usable as standalone or just supposed to be integrated into an application or eg. the community server?

The Kubernetes Docs is supposed to be integrated with other applications (Document Management Systems in particular) which can work with it (Community Server/Nextcloud/Owncloud, for instance). To check Kubernetes Docs prior to the integration part, you can deploy it with its Example service.

> As the documents server image can use an integreated rabbitmq and postgres, these don't have to be deployed if just one instance of the document server is running? 

Kubernetes Docs includes several mutually interconnected images (docservice, proxy, converter) which require Redis, RabbitMQ and PostgreSQL working as external services for them to operate as expected.

**Comment by jakoberpf** [comment]
Hey sorry for the delay, got stuck on the preps (rabbitmq, redis and so). 

Thank you already for this info. So after I setup this documentserver (_**onlyoffice/docs-docservice-de** differs from **onlyoffice/documentserver** in the docker installation as i does not have stuff like rabbitmq integrated?_) I could integrate it into the community server (**onlyoffice/communityserver**). 

Therefore I see two options:
- 1. Migrate the docker installation with the docker image (**onlyoffice/documentserver**) and don't use this helm chart -> no scaling, but no "external services" like rabbitmq, ..., just mysql
- 2. Migrate the docker installation with this helm chart (community, mail and controlpanel image would be the same as in the docker install, but no **onlyoffice/documentserver**?) and integrate the deployment into the **onlyoffice/communityserver** image

Is there documentation how to do this integration into communityserver image?

I have the base service running. I setup the `ds-files` PV and PVC and am installing the helm chart of documentserver with the helm `upgrade --install` command. In order to get the `prepare-ds` job pod running I needed to add ... 
```
  annotations:
    "helm.sh/hook": pre-upgrade,pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
```
to the `documentserver` configmap (because is wasn't created on install otherwise) but now I am stuck because the job cannot install apt packages.

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Err:1 http://deb.debian.org/debian bullseye InRelease
  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Cannot initiate the connection to debian.map.fastlydns.net:80 (2a04:4e42:62::644). - connect (101: Network is unreachable) Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:62::644). - connect (101: Network is unreachable)
Err:2 http://deb.debian.org/debian bullseye-updates InRelease
  Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:62::644). - connect (101: Network is unreachable)
Err:3 http://security.debian.org/debian-security bullseye-security InRelease
  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Cannot initiate the connection to debian.map.fastlydns.net:80 (2a04:4e42:62::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.194.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42:200::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.2.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42:400::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.66.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42:600::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.130.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42::644). - connect (101: Network is unreachable)
Err:4 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease
  Could not connect to apt.postgresql.org:80 (87.238.57.227). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2604:1380:2000:7501::69). - connect (101: Network is unreachable) Could not connect to apt.postgresql.org:80 (217.196.149.55). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2a02:16a8:dc51::55). - connect (101: Network is unreachable) Could not connect to apt.postgresql.org:80 (72.32.157.246). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2a02:c0:301:0:ffff::27). - connect (101: Network is unreachable) Could not connect to apt.postgresql.org:80 (147.75.85.69). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2001:4800:3e1:1::246). - connect (101: Network is unreachable)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Cannot initiate the connection to debian.map.fastlydns.net:80 (2a04:4e42:62::644). - connect (101: Network is unreachable) Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:62::644). - connect (101: Network is unreachable)
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Cannot initiate the connection to debian.map.fastlydns.net:80 (2a04:4e42:62::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.194.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42:200::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.2.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42:400::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.66.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42:600::644). - connect (101: Network is unreachable) Could not connect to security.debian.org:80 (151.101.130.132). - connect (111: Connection refused) Cannot initiate the connection to security.debian.org:80 (2a04:4e42::644). - connect (101: Network is unreachable)
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Cannot initiate the connection to deb.debian.org:80 (2a04:4e42:62::644). - connect (101: Network is unreachable)
W: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/bullseye-pgdg/InRelease  Could not connect to apt.postgresql.org:80 (87.238.57.227). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2604:1380:2000:7501::69). - connect (101: Network is unreachable) Could not connect to apt.postgresql.org:80 (217.196.149.55). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2a02:16a8:dc51::55). - connect (101: Network is unreachable) Could not connect to apt.postgresql.org:80 (72.32.157.246). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2a02:c0:301:0:ffff::27). - connect (101: Network is unreachable) Could not connect to apt.postgresql.org:80 (147.75.85.69). - connect (111: Connection refused) Cannot initiate the connection to apt.postgresql.org:80 (2001:4800:3e1:1::246). - connect (101: Network is unreachable)
W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
```
