### ISSUE TITLE
onlyoffice <=> nextcloud

### ISSUE THREAD

**Issue by rouet** [ONLYOFFICE/Kubernetes-Docs#309]
Hi all,

we have an instance with 2 docservice replica and 2 nextcloud replica (all stuff is deployed with onlyoffice and nextcloud helmcharts)
onlyoffice become unhealthy after some delay and no edition can continue to work.

2 extracts from onlyoffice logs : 

```log
nodeJS - sendServerRequest error: url = https://box.mydomain.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ…;data = {"key":"1743264896","status":3,"users":["oc992s7o213w_*.*@*.*.fr"],"actions":[{"type":0,"userid":"oc992s7o213w_*.*@*.*.fr"}],"lastsave":"2024-05-07T11:24:40.000Z","notmodified":false,"token":"eyJhbGci…"} Error: Error response: statusCode:400; headers:{"server":"nginx/1.25.4","date":"Tue, 07 May 2024 12:26:57 GMT","content-type":"application/json; charset=utf-8","content-length":"27","set-cookie":["oc_sessionPassphrase=LA4Q9…; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc992s7o213w=2113bb256dd0…; path=/; secure; HttpOnly; SameSite=Lax","da2677c5e2708…=1fa0282a5b1b207…; path=/; HttpOnly; Secure; SameSite=None"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","x-request-id":"hvducjxZmavEXHF1QTM8","cache-control":"no-cache, no-store, must-revalidate","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"noindex, nofollow, noindex, nofollow","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block","connection":"close"}; body:
…
sqlQuery error sqlCommand: INSERT INTO task_result (tenant, id, status, statu: error: duplicate key value violates unique constraint "task_result_pkey"
…
```

it worked well before with one replica on each side.

any idea ?

regards

**Comment by alexanderonlyoffice** [comment]
Hi @rouet, please specify the following information: 

1. version of Helm Chart used;
2. versions of the docservice/converter and proxy images used;
3. version of Nextcloud;
4. version of the ONLYOFFICE connector for Nextcloud;
5. please describe more precisely what errors did you see in web interface when trying to open the file for editing, send us the screenshots if possible;
6. send us the Nextcloud log for the time period when the issue occurs 
7. send us the full docservice and converter logs

you can send the log file to support@onlyoffice.com with a note "For technical support 2 lvl" and a link to the GitHub issue.

**Comment by rouet** [comment]
Hi @alexanderonlyoffice,

thanks a lot for your response,
so I began to retrieve the informations you ask for.
when i looked the converter log file, i noticed a error i don't see before : 
`[2024-05-07T12:41:03.919] [ERROR] [4282052329] [oc992s7o213w_s.caraboeuf@ip2i.in2p3.fr] nodeJS - [Error: Unknown system error -122: Unknown system error -122, copyfile '/tmp/ASC_CONVERT202447-1hfue5s.sza2/result/Editor.bin' -> '/var/lib/onlyoffice/documentserver/App_Data/cache/files/data/4282052329/Editor.bin']`
so we checked the volume `ds-files` and we discovered that at the crash date, it was full (our metrics stack is not perfect).

we just extend it now and i think this is the source of our problem and not the replicas.

regards
