### ISSUE TITLE
Add new fonts in docs-converter image

### ISSUE THREAD

**Issue by aurelgcmoi** [ONLYOFFICE/Kubernetes-Docs#314]
Hi, I can't figure out how to add custom fonts for a kubernetes deployment.

The documentation always refers to building a new image [https://github.com/ONLYOFFICE/Kubernetes-Docs/tree/master?tab=readme-ov-file#8-add-custom-fonts](url) but it's for a new complete image of onlyoffice, how can I build a new image for docs-converter only?

Thank you for your help

**Comment by GeorgeONLYOFFICE** [comment]
Hello, as it's mentioned here https://github.com/ONLYOFFICE/Kubernetes-Docs?tab=readme-ov-file#8-add-custom-fonts
you need to follow these steps to rebuild all images https://github.com/ONLYOFFICE/Docker-Docs#building-onlyoffice-docs with required fonts added to the `fonts` directory. It's impossible to rebuild only image for docs-converter, as all images must be rebuilt in this case.

**Comment by aurelgcmoi** [comment]
thanks for your help
