### ISSUE TITLE
Application doesn't work on cluster with disabled ipv6

### ISSUE THREAD

**Issue by agolybev** [ONLYOFFICE/Kubernetes-Docs#32]

**Comment by Westat-Transportation** [comment]
I believe I am hitting this problem on the latest version of the helm chart.  Can you tell me if there is anyway to work around this problem via the values yaml file?

Here's the error I am seeing on the docservice pod:
```
Defaulted container "proxy" out of: proxy, docservice
2023/05/30 19:58:16 [emerg] 1#1: socket() [::]:8888 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:8888 failed (97: Address family not supported by protocol)
```

**Comment by Westat-Transportation** [comment]
Is the docker file used to build the img used by the chart somewhere on GitHub? Thanks.

**Comment by VyacheslavSemin** [comment]
Fixed [here](https://github.com/ONLYOFFICE/Docker-Docs/pull/86)

**Comment by alexanderonlyoffice** [comment]
The problem was fixed in the above mentioned release, so we are closing the issue.
