### ISSUE TITLE
Allow adding extra environment variables and volumes to containers

### ISSUE THREAD

**Issue by keliansb** [ONLYOFFICE/Kubernetes-Docs#325]
Hello

We are trying to configure ONLYOFFICE Docs to connect to a PostgreSQL database deployed eternally with TLS enabled (and required).

To enabled PostgreSQL TLS connections in ONLYOFFICE Docs we added the following configuration to the `local.json` file (thanks to [this issue](https://github.com/ONLYOFFICE/Kubernetes-Docs/issues/255)) :
```
{"services": { "CoAuthoring": { "sql": { "pgPoolExtraOptions": { "ssl": true }}}}}
```

However the following error is returned by `docservice` :
```
[2024-10-17T07:16:40.440] [WARN] [docId] [userId] nodeJS - sqlQuery error sqlCommand: SELECT column_name as "column_name" FROM informati: Error: unable to get local issuer certificate
    at /snapshot/server/DocService/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2024-10-17T07:16:40.440] [ERROR] [docId] [userId] nodeJS - getTableColumns error: Error: unable to get local issuer certificate
    at /snapshot/server/DocService/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

We managed to solve this issue by mounting a ConfigMap containing the root certificate of our internal certificate authority to the container, and then by adding the following environment variable :
```
envs:
  - name: NODE_EXTRA_CA_CERTS                                                                                                                                                                           
    value: <path_to_configmap_file>
```

In order to not do this manually it would be nice for the chart to support adding extra environment variables and volumes to the containers.

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

Thank you for your feedback and suggestion. We will add it to our roadmap to make it possible in future.

**Comment by GeorgeONLYOFFICE** [comment]
Hello,

As promised, we have added the corresponding variables, e.g.
[converter.extraEnvVars](https://github.com/ONLYOFFICE/Kubernetes-Docs/blob/master/values.yaml#L993C6-L998) 
[converter.extraVolumes](https://github.com/ONLYOFFICE/Kubernetes-Docs/blob/master/values.yaml#L934-L940) 
[converter.extraVolumeMounts](https://github.com/ONLYOFFICE/Kubernetes-Docs/blob/master/values.yaml#L999-L1005) for converter, etc.

**Comment by keliansb** [comment]
Thank you @GeorgeONLYOFFICE! Just tested it with latest chart version and it works. I close this issue.
