### ISSUE TITLE
question around release v4.3.0

### ISSUE THREAD

**Issue by wkloucek** [ONLYOFFICE/Kubernetes-Docs#326]
I have a short question around release v4.3.0:

I see the release branch has been merged to `master` branch: https://github.com/ONLYOFFICE/Kubernetes-Docs/commit/cd7384a2198ff108299397ef38a828566283b3bb

But currently I don't see a tag `v4.3.0` on the repository. When will you tag the repository?

@agolybev @alexonlyoffice

**Comment by alexonlyoffice** [comment]
@wkloucek, thank you for reporting. Tag 4.3.0 was added.

**Comment by wkloucek** [comment]
Thanks, that was quick
