### ISSUE TITLE
Connection in license file is multiplied by docservice nodes

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Kubernetes-Docs#4]
If we have license for 1000 connection and deploy two `docservice` nodes - this cluster handle 2000 connection

This mechanism need to be redone

**Comment by agolybev** [comment]
Fixed with ONLYOFFICE Docs v6.0.0

**Comment by ShockwaveNN** [comment]
Currently I have no ability to generate 1000 connection and recheck this problem
And since problem solved not in k8s, but in base ONLYOFFICE DocumentServer product, I think this issue can be closed

**Comment by ShockwaveNN** [comment]
Just rechecked using default trial empty license (`kubectl create secret generic license`)
This license shold allow 20 connections, but only 40ish browser tab warn me:
![image](https://user-images.githubusercontent.com/668524/100349500-9ea66800-2ff9-11eb-9a1d-dce1ff763a57.png)

**Comment by ShockwaveNN** [comment]
Setup cluster with license with `"connections":30,` options

And still 40 browser windows are opened until warning. This is strange

Mabye license reading is not working

**Comment by ShockwaveNN** [comment]
connected to pod via
```
kubectl exec -it docservice-7f676f79c9-htvqh bash
```

And run
```
curl http://docservice:8000/info/info.json
```

Result was containing `"connections":20`

I've checked `secrets` as described here: https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#decoding-secret
```
kubectl get secret license -o jsonpath='{.data}'
```

And decoding value and value correct

**Comment by agolybev** [comment]
Images onlyoffice/docs-xxx:6.0.2 based on community version of ONLYOFFICE Docs, so connections were limited to 20 per pod. Also, the community version doesn't support clustering so 'docservice' pods work independently of each other and it looks like multiplicate connections of pods number.

Images changed to onlyoffice/docs-xxx:6.0.2.5 based on the commercial version of ONLYOFFICE Docs and the problem was fixed.

**Comment by ShockwaveNN** [comment]
Checked empty license, 20 connection is ok, 21 and greater is correct warning message

![image](https://user-images.githubusercontent.com/668524/100725581-4397bb00-33d5-11eb-9f81-9f44df405f7e.png)

**Comment by ShockwaveNN** [comment]
And finally recheck license with 30 connection
30 browser tabs are ok, 31 browser tab is showing License Limit Reached, as should

**Comment by ShockwaveNN** [comment]
So now everything is fine, I'll close the issue
