### ISSUE TITLE
Different list of files on test example

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Kubernetes-Docs#6]
Started example service and randomly created some files

Seems that each refresh of example page I have three ranom state:

1. one docx file
2. one docx, one xlsx file
3. no files at all
![output](https://user-images.githubusercontent.com/668524/79581835-a604ab00-80d3-11ea-9743-f84d22a10714.gif)

**Comment by VyacheslavSemin** [comment]
Fixed [here](https://github.com/ONLYOFFICE/Docker-Docs/pull/38)
