### ISSUE TITLE
No auto-scaling support

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/Kubernetes-Docs#7]
If some pod have a lot of perforamnce load currently only way to add more power - manually spinup some more nodes.

Need support of autoscaling

**Comment by GeorgeONLYOFFICE** [comment]
To increase the amount of replicas in case of еру increased resourses usage it's possible
to use Horizontal Pod Autoscaling. You can find more information about it [here](https://github.com/ONLYOFFICE/Kubernetes-Docs#61-horizontal-pod-autoscaling).
