### ISSUE TITLE
ECONNREFUSED while uploading non-ooxml file in test example

### ISSUE THREAD

**Issue by aurelgcmoi** [ONLYOFFICE/Kubernetes-Docs#76]
When I upload a file in a format that needs converting (eg: .odt, .odp...) I receive an error:

![image](https://user-images.githubusercontent.com/64071546/142865137-3c49e923-385e-4cd1-a2a8-23ea96a1eb17.png)
 
I tried modifying the DS_URL in example.yaml configmap but nothing seems to work

**Comment by ShockwaveNN** [comment]
Hi, thank you for your report

I can confirm, this issue is actual for me as well
I've created issue 54164 in our internal issue tracker
